#server.port=8081
spring.application.name=userManagemnet
spring.datasource.url=jdbc:postgresql://localhost:5432/discuessit
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
 spring.jpa.properties.hibernate.default_schema=usermanagement
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.property-naming-strategy= SNAKE_CASE
